[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "uio_ml"
version = "0.1.0"

[tool.setuptools.packages.find]
where = ["."]
include = ["ml_project1*", , "ml_project2*"]
